### ISSUE TITLE
Create interface/abstraction to manage extension modules

### ISSUE THREAD

**Issue by nrempel** [masalachai/epp-client#14]
[rfc5730](https://datatracker.ietf.org/doc/html/rfc5730#page-16) defines an extension framework to extend the protocol via:
- Protocol extension
- Object extension
- Command-Response extension

We will need a way to define these 3 different kinds of extensions. Currently, `EppClientConnection` contains information about which `<svcExtension>` elements should be sent to the server. I think this value should likely be derived from which extension modules are loaded. Additionally, the `<svcs>` element is currently hardcoded to contain host, contact, and domain objects. We will need a way to load more objects dynamically via "Object extensions".

Some other thoughts and things we will need to consider:
- Login request should send appropriate svcs and svcExtension elements based on which extension module is loaded
- Greeting response from EPP server contains list of supported objects and extensions. epp-client should warn if extension module is not present for objURI? epp-client should panic if extension module is not present for extURI?
  - If server supports an extension, then the client *must* use the extension in order to read/modify that resource (e.g., VeriSign uses their NameStore extension and a client must implement this extension in order to utilize `domain:check`

**Comment by nrempel** [comment]
I just noticed you do have an example of a command with extension here: https://github.com/nrempel/epp-client/blob/c5e467b0230c40e2e4876b4542a06fe5a52e0fc7/epp-client/src/epp/request/domain/rgp/report.rs#L136

This looks good. I think this is a good approach for Command-response extension case.

But I do wonder about the semantics of a command changing if an extension is loaded for that command. Take the [NameStore](https://www.verisign.com/assets/epp-sdk/verisign_epp-extension_namestoreext_v01.html) extension for instance:

```xml
C:<?xml version="1.0" encoding="UTF-8" standalone="no"?>
C:<epp xmlns="urn:ietf:params:xml:ns:epp-1.0">
C:  <command>
C:    <check>
C:      <domain:check
C:       xmlns:domain="urn:ietf:params:xml:ns:domain-1.0">
C:        <domain:name>EXAMPLE1.TLD</domain:name>
C:        <domain:name>EXAMPLE2.TLD</domain:name>
C:        <domain:name>EXAMPLE3.TLD</domain:name>
C:      </domain:check>
C:    </check>
C:    <extension>
C:      <namestoreExt:namestoreExt
C:       xmlns:namestoreExt=
C:       "http://www.verisign-grs.com/epp/namestoreExt-1.1">
C:         <namestoreExt:subProduct>TLD</namestoreExt:subProduct>
C:      </namestoreExt:namestoreExt>
C:    </extension>
C:    <clTRID>ABC-12345</clTRID>
C:  </command>
C:</epp>
```

We will need some way of sending the appropriate payload. If the `<greeting>` response includes `<extURI>http://www.verisign-grs.com/epp/namestoreExt-1.1</extURI>`, the the client must include the extension when issuing a `<check>` command. However, by including this extension then the caller would need to pass in the relevant `subProduct` information as well which would change any relevant function signatures.

Should the caller be responsible for inspecting the `<greeting>` response, checking for `namestoreExt`, and then instead of constructing an `EppDomainCheck` request object to issue a `domain:check` construct something like `EppDomainNameStoreCheck`?

**Comment by masalachai** [comment]
>by including this extension then the caller would need to pass in the relevant subProduct information as well which would change any relevant function signatures.

Yes, I haven't yet figured out what the ideal way to do this is yet. The way it is right now, for example, for namestore, you'd have to have a new request type for the request with the extension, so yes something like `EppNamestoreDomainCheck` which would currently be an alias for `EppObject<CommandWithExtension<DomainCheck, NamestoreDomainCheckExtension>>`.

I thought of adding a type arg to the `EppDomainCheck` alias that'd either accept an extension or not, so you'd use `EppDomainCheck<NoExtension>` and `EppDomainCheck<NamestoreDomainCheckExtension>` where for the latter you'd be able to set an extension instance of that type in the request, but the `NoExtension` part looks kind of ugly and superfluous, so I didn't go with that.

Let me know if you have other ideas about how to implement this.

>Should the caller be responsible for inspecting the <greeting> response

Well, the caller does need to pass in data specific to the `namestore` extension when making the call, so they would know that they have to use an `EppNamestoreDomainCheck` instead of `EppDomainCheck`. I don't think there's a way around this.

**Comment by nrempel** [comment]
I just took a pass at using the current `CommandWithExtension` method for domain. In the case of NameStore, it will need to be implemented for each object mapping so I think there is too much boilerplate here.

I'm going to give your suggestion a try of having something like a `set_extension` method/
