### ISSUE TITLE
Handle timeouts, reconnect

### ISSUE THREAD

**Issue by nrempel** [masalachai/epp-client#62]
I think we should handle reconnecting in case of a timeout. Perhaps we can send `hello` on a timer to check the connection status: https://datatracker.ietf.org/doc/html/rfc5730#section-2.3

**Comment by djc** [comment]
I think maybe by default we shouldn't try to keep the connection alive, but instead just reconnect if we want to do something and it turns out the connection has timed out? Otherwise we might be keeping connections open to registrars with which we don't have many transactions.

**Comment by masalachai** [comment]
Generally it's probably a better idea to only keep connections active when needed, but since most registries allow you to keep the connection active even if it isn't busy, it seems to be common requirement for registrars to reduce connection re-negotiation as much as possible for the transactions to be faster whenever they happen, even if the connection isn't otherwise too busy.
